### ISSUE TITLE
Provide `dotnet new` template for Web API

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#10]
Provide a [custom `dotnet new`](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates) template which configures a Web API with minimal requirements.

The template should be calles `arcus-webapi`.

## Features in the template

- [X] Plug in [exception middleware](https://webapi.arcus-azure.net/features/logging)
- [X] Configure content negotiation to only support `application/json`
- [x] Setup Swagger generation
- [x] Setup Swagger UI (but disable for PROD env)
- [X] Configure [health checks](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2) *(middleware only)*
- [X] Provide health endpoint *(based on [info gained via health checks](https://www.codit.eu/blog/documenting-asp-net-core-health-checks-with-openapi/)*
	- Fully documented according to our guidelines
- [x] Provide a working Dockerfile
- [X] Build a default logger

The template should not provide any authentication by default but should provide a comment that warns about this and point to [Arcus WebAPI and Shared Access Key](https://webapi.arcus-azure.net/features/security/auth/shared-access-key).

## Requirements

We should provide a CI that performs following steps:
1. Create project based on template via `dotnet new arcus-webapi`
2. Build a Docker container based on `Dockerfile`
3. Run Docker container
4. Get the health of the container

## Good reads

- https://rehansaeed.com/custom-project-templates-using-dotnet-new/

**Comment by tomkerkhove** [comment]
I'm assigning this to you if that is ok @stijnmoreels 	.

However, let's take it step by step and provide the boilerplate with just the exception handling, for example, and already create a PR.

It's added to our Arcus roadmap but let's finalize the items that we've discussed today 
 first if that's ok.

**Comment by tomkerkhove** [comment]
@stijnmoreels If I understand it correctly we are good to go, except for the correlation.

Is that correct?

If so, would be good if we started working on the NuGet release to ship a v0.1.

**Comment by stijnmoreels** [comment]
Yes, besides correlation all the tasks are done. A closer look at the title, description, summary, icon, ... would be a good idea though.

What else must be done for the NuGet release?

**Comment by tomkerkhove** [comment]
> A closer look at the title, description, summary, icon, ... would be a good idea though.

What are you referring to here?

**Comment by tomkerkhove** [comment]
> What else must be done for the NuGet release?

Nothing other than creating the release pipeline!

**Comment by stijnmoreels** [comment]
Oh, I mean the metadata of the nuget package for the template.

**Comment by tomkerkhove** [comment]
I'll have a look, thanks!

**Comment by tomkerkhove** [comment]
Moving out the correlation into #30 so we can ship a first version and add this later on.
