### ISSUE TITLE
dotnet new arcus-webapi creates new project in current directory

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#107]
When executing the command

```cmd
dotnet new arcus-webapi --name api.test
```
the new project is created directly in the current folder.  I think it would be better to create the new project in a (new) subfolder of the current folder.   So when executing the above command, a subfolder `api.test` should be created and the project should be created in that folder.

I think this makes it a bit more user-friendly and it is also in line with the `webapi` template that is provided by MS.

**Comment by tomkerkhove** [comment]
Good idea - Can we do that @stijnmoreels?

I'd do that for both templates

**Comment by tomkerkhove** [comment]
Think we'll need to use [`target`](https://github.com/dotnet/templating/wiki/Reference-for-template.json#source-definition)

**Comment by stijnmoreels** [comment]
> Think we'll need to use [`target`](https://github.com/dotnet/templating/wiki/Reference-for-template.json#source-definition)

I think we can just add `"preferNameDirectory": true` to the `.template.json`.

**Comment by tomkerkhove** [comment]
Also fine for me
