### ISSUE TITLE
Projects created with dotnet new webapi are missing a Docker run profile

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#108]
When I create a new Arcus webapi project using the `dotnet new arcus-webapi` command, a new api project is created as expected.

However, since the Api project supports Docker (a dockerfile is created), I would also expect that there's a profile available which allows me to run/test my API from Visual Studio using Docker.

When I create a new Arcus WebApi project, following profiles are available:

![image](https://user-images.githubusercontent.com/3605786/75353166-316b7800-58ab-11ea-9058-4d369f32eda6.png)

When I create a new Web Api project via Visual Studio and I enable Docker support these profiles are available:

![image](https://user-images.githubusercontent.com/3605786/75353731-27964480-58ac-11ea-8a69-4d5577212f06.png)

It would be nice if the Docker profile is also available when creating a new project using the arcus-webapi template and that this Docker profile is the default profile.

**Comment by tomkerkhove** [comment]
Good idea!

I don't know where these are stored, is that in `Properties > Launchsettings.json`?

**Comment by fgheysels** [comment]
To achieve this, you indeed need to provide a configuration in `Launchsettings.json`
Next to that, the csproj file must also contain a `DockerDefaultTargetOS` tag.  For instance:

```
<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
```

and, the `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` package must be referenced.

**Comment by tomkerkhove** [comment]
It looks like we do have them, but are in the `AuthoringMode` section: https://github.com/arcus-azure/arcus.templates/blob/master/src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj#L7

That means it's only used for our development, right @stijnmoreels?

**Comment by stijnmoreels** [comment]
> It looks like we do have them, but are in the `AuthoringMode` section: https://github.com/arcus-azure/arcus.templates/blob/master/src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj#L7
> 
> That means it's only used for our development, right @stijnmoreels?

Yes, but we could include them in the resulting project if this is indeed required.

**Comment by fgheysels** [comment]
> > It looks like we do have them, but are in the `AuthoringMode` section: https://github.com/arcus-azure/arcus.templates/blob/master/src/Arcus.Templates.WebApi/Arcus.Templates.WebApi.csproj#L7
> > That means it's only used for our development, right @stijnmoreels?
> 
> Yes, but we could include them in the resulting project if this is indeed required.

I think this is required.  When creating an API that will eventually run as a docker container, it is always helpful to be able to easily run it as a container locally during develompment.

**Comment by stijnmoreels** [comment]
@tomkerkhove , I'll close this?

**Comment by tomkerkhove** [comment]
Why is that? The PR is still open?

**Comment by tomkerkhove** [comment]
Oh it got merged, nevermind! I would need to check if it's fully working now
