### ISSUE TITLE
Provide capability to opt-in for shared access key during generation

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#12]
Provide capability to opt-in for shared access key during generation so that it is already configured.

[.NET Boxed](https://github.com/Dotnet-Boxed/Templates/blob/master/Docs/API.md) is a good example where they allow you to configure what to include or not.

**Comment by tomkerkhove** [comment]
Turns out you can provide "options", we can use that @toonvanhoutte @SamVanhoutte

**Comment by stijnmoreels** [comment]
Not entirely done I think, since we need perhaps docs for this?

**Comment by tomkerkhove** [comment]
That is correct, but I think this is applicable to the other issue as well.

**Comment by tomkerkhove** [comment]
This is done and documented here: https://templates.arcus-azure.net/features/web-api-template#configuration

Ok to close for you @stijnmoreels ?

**Comment by tomkerkhove** [comment]
This is done
