### ISSUE TITLE
Use enrichers from Arcus Observability

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#138]
Use enrichers from Arcus Observability

**Comment by stijnmoreels** [comment]
Which ones?
- [ ] `VersionEnricher`
- [ ] `ApplicationEnricher`
- [ ] `CorrelationInfoEnricher`
- [ ] `KubernetesEnricher`

**Comment by tomkerkhove** [comment]
- Always include `VersionEnricher`
- Leaning towards always including for `ApplicationEnricher` with decent sample value, such as "API" & "Service Bus Worker"
- Include `CorrelationInfoEnricher` when using correlation (existing flag)
- Not sure about Kubernetes enricher, might be opt-in by using `--kubernetes-ready` flag or so

**Comment by stijnmoreels** [comment]
> Not sure about Kubernetes enricher, might be opt-in by using --kubernetes-ready flag or so

Maybe to specific and "too easy to add" to make it as a project option?

**Comment by tomkerkhove** [comment]
Yes, let's leave out for now
