### ISSUE TITLE
Documentation bug: configuration flags for new Arcus WebApi Template

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus.templates#143]
Hello all, 

I have run this on mac, though doubt that this would be relevant information.
Execution steps to create a new WebApi project:
```
dotnet new arcus-webapi --name ReproApi - au SharedAccessKey -ia true -lo Serilog
```
But executing this fails with the following exception, so I think there's a mismatch between the actual code / logic and the docs.
```
Invalid input switch:
  -au
  SharedAccessKey
  -ia
  true
  -lo
  Serilog
Arcus WebAPI (C#)
Author: Arcus
Options:                                                                                                                
  -A|--Authentication  Choose whether to use an authentication mechanism and which authentication to use                
                           SharedAccessKey    - Adds a shared access key authentication mechanism to the web API project
                           None               - No authentication mechanism is added to the web API project             
                       Default: None   
```
This is the documentation page: 
```md
-au|--authentication (default None)
SharedAccessKey: adds shared access key authentication mechanism to the API project
Certificate: adds client certificate authentication mechanism to the API project
JWT: adds JWT (JSON Web Token) authentication mechanism to the API project
None: no authentication configured on the API project.
-ia|--include-appsettings (default false): includes a appsettings.json file to the web API project.
-ec|--exclude-correlation (default false): excludes the capability to correlate between HTTP requests/responses from the API project.
-eo|--exclude-openApi (default false): exclude the ASP.NET OpenAPI docs generation and UI from API project.
-lo|--logging (default Console)
Console: no extra logging mechanism except for the default console logging will be added to the web API project.
Serilog: adds Serilog as logging mechanism with request logging to the web API project.
```

**Comment by SamVanhoutte** [comment]
@tomkerkhove : happy to fix/PR myself, but wanted to log it already.  also maybe @renebik wants to take this one, as I believe you had looked at the docs before ?

**Comment by stijnmoreels** [comment]
Hmm, not sure. I can't reproduce it with the recent version I have on my machine
![image](https://user-images.githubusercontent.com/9039753/77509939-fb9bbe00-6e6d-11ea-91e5-d227c9abcf8e.png)

**Comment by tomkerkhove** [comment]
Thanks for reporting @SamVanhoutte!

@stijnmoreels Is there a way to get the version of installed template? If so, let's put some guidance in the README and issue template to add it to the report.

**Comment by tomkerkhove** [comment]
> In the example you showed, there's an extra whitespace between `-` and the `au`... is that a mistake here or a mistake in your statement?

But will most probably be this indeed

**Comment by stijnmoreels** [comment]
> @stijnmoreels Is there a way to get the version of installed template? If so, let's put some guidance in the README and issue template to add it to the report.

With `dotnet new -u` you see the list of installed templates and their versions.

**Comment by stijnmoreels** [comment]
Ah, I think I know...
It's propably an older version that @SamVanhoutte is using...

**Comment by tomkerkhove** [comment]
The issue will be the space so let's just wait until Sam comes back to us and re-evaluate if that's not it

**Comment by SamVanhoutte** [comment]
i ran (this morning) the dotnet install command, so could it be that the old version is somewhere referenced/cached still?  (mac os)

**Comment by SamVanhoutte** [comment]
> Hmm, not sure. I can't reproduce it with the recent version I have on my machine
> ![image](https://user-images.githubusercontent.com/9039753/77509939-fb9bbe00-6e6d-11ea-91e5-d227c9abcf8e.png)
> 
> In the example you showed, there's an extra whitespace between `-` and the `au`... is that a mistake here or a mistake in your statement?

it is note related to that (maybe copy/past to here, but definitely not on my laptop).  so I have an old version, I think

**Comment by stijnmoreels** [comment]
> i ran (this morning) the dotnet install command, so could it be that the old version is somewhere referenced/cached still? (mac os)

No, it's not that. The most recent version we have published still has that pascal case commands. So, I guess bc we only have a single doc site and no stage area, the docs are now showing the current state of the repo and not the state of the most recent published package.

**Comment by stijnmoreels** [comment]
So the best thing you can do @SamVanhoutte , to see the current available commands for your version, is using the `--help` command.

**Comment by SamVanhoutte** [comment]
@stijnmoreels - thanks for the suggestion and I will, indeed.  however, it would be good (not urgent, though) to find a good way to synchronize the docs with the latest release, as otherwise this might trigger other people to make the same mistakes I did

**Comment by SamVanhoutte** [comment]
I just ran the `--help` option and I get the following output, so I believe it is an outdated version on my laptop?  Any idea how to "force update" a template?

![image](https://user-images.githubusercontent.com/3539605/77579371-7ef2f900-6eda-11ea-9596-6d60396c49b6.png)

**Comment by tomkerkhove** [comment]
Can you try this please?
https://github.com/dotnet/templating/issues/1538#issuecomment-591845321

Seems like an open bug in .NET

**Comment by SamVanhoutte** [comment]
hmmm, strange - i tried the following code:
```
dotnet new -u Arcus.Templates.WebApi
nuget locals http-cache -clear
dotnet new -i Arcus.Templates.WebApi
```
No errors on those lines, but when I ran the `dotnet new arcus-webapi --help`, I got the same output as above

**Comment by tomkerkhove** [comment]
Ok I took a step back and a sip of ☕ and this is normal since we've only shipped [v0.1.1](https://www.nuget.org/packages/Arcus.Templates.WebApi/0.1.1) and [v0.2](https://github.com/arcus-azure/arcus.templates/milestone/3) work is done but not shipped yet.

Conclusion:
- We need to better document with respect to what version introduces it
- We need to ship v0.2 - Ok for you @stijnmoreels?
- We need to improve our support

**Comment by SamVanhoutte** [comment]
Thanks,
* Is there a way to only publish the docs, in synchronization with the release process?
* Is there a way to show the template version, when using the `--help`argument?

**Comment by stijnmoreels** [comment]
> * Is there a way to show the template version, when using the `--help`argument?

Using the `dotnet new -u` command shows all installed packages with their versions.
