### ISSUE TITLE
Update issue template to list version of installed packages

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#144]
Update issue template to list version of installed packages so that we have an idea what the user is using.

Example: https://github.com/tomkerkhove/promitor/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md#specifications

Initially required in #143

**Comment by stijnmoreels** [comment]
Hmm, isn't that already the case?
![image](https://user-images.githubusercontent.com/9039753/77521453-fdbc4780-6e82-11ea-94ce-65226e56e8b1.png)

**Comment by tomkerkhove** [comment]
Ok fair enough - Then the issue is that it's in `.github/.github/ISSUE_TEMPLATE` which is why it's not showing it
