### ISSUE TITLE
Document what version introduces a specific feature

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#147]
**Is your feature request related to a problem? Please describe.**
Document what version introduces a specific feature so that people know what to expect.

**Describe the solution you'd like**
- Only publish documentation for new features when a new version is released
- Provide indication in documentation what version introduces the feature

**Describe alternatives you've considered**
None

**Comment by tomkerkhove** [comment]
If we only publish documentation when a new version is being released you can still be confused because it's not clear what was new in the version you have and the docs.

Possibilities I see are:
- Version URLs
	- That's what I do on Promitor
- Introduce a changelog similar to [this](http://changelog.promitor.io/) or [`CHANGELOG.md`](https://github.com/kedacore/keda/blob/master/CHANGELOG.md)
- Surfacing it in the docs
	- That's what I do on Promitor
	- Example (rough approach to prove point):
  ![image](https://user-images.githubusercontent.com/4345663/77627561-640a9e00-6f47-11ea-8cdc-34498c855266.png)


However, the changelog mainly serves other purposes imo

**Comment by tomkerkhove** [comment]
Thoughts @SamVanhoutte ?

**Comment by SamVanhoutte** [comment]
having a version history in the docs is definitely good. 
however it would be nice (don't know how feasible) to get a warning when you run the template that there is a new version released and you should upgrade?

**Comment by tomkerkhove** [comment]
I think that would be more a .NET feature rather than something we can provide, but will open an issue for that.

**Comment by stijnmoreels** [comment]
> Thoughts @SamVanhoutte @stijnmoreels?

Yes, I like the example. I'ld go for that. + showing the version in the help command.
