### ISSUE TITLE
Determine if we can warn users about new template versions being available

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#149]
**Is your feature request related to a problem? Please describe.**
Determine if we can warn users about new template versions being available which they should upgrade to.

**Describe the solution you'd like**
Warning in output

**Describe alternatives you've considered**
None

**Comment by stijnmoreels** [comment]
I think I found a way to show this warning when we do.a.`dotnrt new` command. But it's not possible yet I think to manipulate the functionality to do.something when running the `--help`.

Would that be enough? Just when a new project is being created?

**Comment by tomkerkhove** [comment]
Sounds good to me, better like that than nothing ;)

**Comment by stijnmoreels** [comment]
No usable user-friendly way available yet. Closing...
