### ISSUE TITLE
Document generated security mechanism in OpenAPI

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#154]
**Is your feature request related to a problem? Please describe.**
Document generated security mechanism in OpenAPI when applicable.

**Describe the solution you'd like**
`AddSecurityDefinition` should be used when configuring OpenAPI docs for API key authentication.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements

**Describe alternatives you've considered**

**Additional context**

**Comment by stijnmoreels** [comment]
So only the security definitions have to be added when any authentication mechanism was used?

**Comment by tomkerkhove** [comment]
Yes, imagine the template is generated; OpenAPI UI & spec should list the chosen authentication mechanism so that it's clear how to use the API.
