### ISSUE TITLE
Debug session does not start

### ISSUE THREAD

**Issue by MassimoC** [arcus-azure/arcus.templates#156]
**Describe the bug**
Could not find the global property 'UserSecretsId' in MSBuild project 

**To Reproduce**
on a clean machine I had
* dotnet new --install Arcus.Templates.WebApi
* dotnet new arcus-webapi --name Hello.Vegas
* build the project
* start a debugging session (docker)

Debug session does not start. 
> ERROR :"Could not find the global property 'UserSecretsId' in MSBuild project 'C:\Temp\Codit\Arcus\...'. Ensure this property is set in the project or use the '--id' command line option."

**Expected behavior**
Being able to get data from the health endpoint

**Additional context**
Latest version
Adding the UserSecretId property **fixes the problem**.
![2020-04-01_17-28-32](https://user-images.githubusercontent.com/8393694/78156932-b19f7300-743f-11ea-9c81-7c0b95b42615.png)

**Comment by tomkerkhove** [comment]
That's odd.. So you just did a dotnet new and it failed because of that?

**Comment by MassimoC** [comment]
I did 4 steps:
OK) dotnet new --install Arcus.Templates.WebApi
OK) dotnet new arcus-webapi --name Hello.Vegas
OK) build the project
ERROR) start a debugging session (docker)

Same error was reported from a colleague

**Comment by fgheysels** [comment]
I can confirm; I have the same issue.
I created a new project yesterday using the webapi template, and when I try to debug it locally using the Docker profile, I get the following error

> Could not find the global property 'UserSecretsId' in MSBuild project

When I try to debug it using the IIS Express profile, it works.  (As is, I am able to run and debug the project)

**Comment by tomkerkhove** [comment]
I think it has to do with the fact that it exposes over HTTPS by default and needs the local cert, @stijnmoreels  or myself will have a look at it

**Comment by tomkerkhove** [comment]
Thanks for reporting!

**Comment by tomkerkhove** [comment]
@MassimoC @fgheysels as a mitigation you can run `dotnet user-secrets init` in project folder
