### ISSUE TITLE
Enums are not accepted as strings

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#158]
**Describe the bug**
Despite the fact that there is some code in `Startup` which describes that enums should be serialized /deserialized as strings, string enum values are not accepted.

**To Reproduce**
- Create a new webapi project using `dotnet new arcus-webapi --name enumtest`

- Extend the existing HealthController with a POST operation that accepts an enum in the body
```csharp
[HttpPost]
public IActionResult Test([FromBody] SomeEnum x)
{
    return Ok(x);
}

public enum SomeEnum
{
   One,
   Two,
   Three
}
 ```

- Try the method using the swagger UI, and pass in a string in the body (for instance "One")

- A bad request is returned with the following response:
  > "errors": {
    "$": [
      "The JSON value could not be converted to enumtest.Controllers.SomeEnum. Path: $ | LineNumber: 0 | BytePositionInLine: 5."
    ]
  }

- When you specify 0, 1 or 2 in the body, the operation succeeds and returns the string serialized value of the enum.

**Expected behavior**
I'd expect that string values are accepted and correctly deserialized to the corresponding enum value.

**Fix**
The expected behavior is realized by adding specifying that the JsonStringEnumConverter should be used:

```csharp
services.AddControllers(options => 
{
        options.ReturnHttpNotAcceptable = true;
        options.RespectBrowserAcceptHeader = true;

        RestrictToJsonContentType(options);
        AddEnumAsStringRepresentation(options);
}).AddJsonOptions(options => options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
```
Don't know what should be done with the `AddEnumAsStringRepresentation` invocation in the AddControllers action.

**Comment by tomkerkhove** [comment]
Confirmed it locally that fix is required, just wondering why our `AddEnumAsStringRepresentation`method doesn't help 🤔 

Might be better to move to the new method then or do you have some insights @stijnmoreels?

**Comment by fgheysels** [comment]
> Confirmed it locally that fix is required, just wondering why our `AddEnumAsStringRepresentation`method doesn't help 🤔
> 
> Might be better to move to the new method then or do you have some insights @stijnmoreels?

I think this is because the `JsonStringEnumConverter` is only added to the OutputFormatters
