### ISSUE TITLE
Should API projects generated with arcus-webapi template use Newtonsoft.Json instead of Json.Text

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#159]
It seems that the new Json.Text serializer that is used by default in ASP.NET has a lot of limitations as opposed to the Newtonsoft.Json serializer.

I'm wondering if we shouldn't specify the Newtonsof.Json serializer for projects that are created with arcus-webapi.

Some limitations where I ran into today:
- no out of the box support to [serialize/deserialize Timespan types](https://github.com/dotnet/runtime/issues/29932).  You have to create your own converter for it.  (Not such a big issue but ...)
- [No support](https://github.com/dotnet/runtime/issues/31081) for `EnumMember` attributes to control how enum values should be serialized.  There is a [workaround ](https://blog.macrosssoftware.com/index.php/2019/10/09/net-core-3-system-text-json-enummemberattribute-serialization/)for it, but it's yet another external package.
- Swashbuckle example's don't seem to work well when using the Json.Text serializer as well.  When creating custom examples for a type which has enum properties, those enum-values are not serialized as a string although you have specified that enums should be formatted as a string.  (Ok, this is most likely a problem in Swashbuckle.Filters, but it is confusing :) ).

So the question is, should we make sure that we use Newtonsoft.Json as the JSON serializer by specifying:

```csharp
 services.AddControllers(options =>
{
   ...
}).AddNewtonsoftJson(o =>
{
    o.SerializerSettings.Converters.Add(new StringEnumConverter());
});
```

**Comment by fgheysels** [comment]
I'm confused with my 3rd point in this issue.  Since, when I read [this](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft), I'd assume that swashbuckle works with Json.Text in the version that we're using (>5.0.0) but it doesn't look like it's doing that.

I've created a custom Json.Text serializer for specifying that Timespans should be serialized correctly, but it doesn't look like this is happening.
Will investigate a bit more when I have a bit of time.

**Comment by tomkerkhove** [comment]
Ok thanks, that's fair I think.

This is not something you'd easily change.

**Comment by stijnmoreels** [comment]
Close in favor of https://github.com/arcus-azure/arcus.templates/discussions/277
