### ISSUE TITLE
Change logging to use Serilog by default

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#193]
**Is your feature request related to a problem? Please describe.**
Change logging to use Serilog by default as it provides more functionality as the console one and is more aligned with our other templates.

**Comment by tomkerkhove** [comment]
Thoughts?

**Comment by stijnmoreels** [comment]
Yes! I understand it would be better maybe!

**Comment by stijnmoreels** [comment]
I'll assume it is agreed and can be implemented.
