### ISSUE TITLE
Proposal - add observability telemetry core by default in packages?

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.templates#210]
Should we include besides the optional Application Insights Serilog sink, our telemetry core package by default?

**Comment by tomkerkhove** [comment]
If they are used I'd say yes, but if they are not then I think we should leave them out.

**Comment by stijnmoreels** [comment]
The package is not used as of yet, the Application Insights Serilog sink is though; that's why I was wondering if we would benefit from the extensions in the core telemetry package (metric, dependency, security, event...).

But we can leave that up to them of course.

**Comment by tomkerkhove** [comment]
Fair point, let's just add it and give them the power! 🔨
