### ISSUE TITLE
Testing - Project option test cases

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.templates#24]
Now, in the integration tests we test the simple possible way of creating a project from the template (without any options).

It would be reasonable if the integration tests consists of several test cases that each creates a new project with one or more options specified and then takes some actions on that new created project to see if the selected options reflect in a changed behavior.

Ex.: when choosing for a authentication mechanism, testing if we indeed have to configure the correct authentication.

**Comment by tomkerkhove** [comment]
That's a good idea, we would then have to add a stage per scenario and run tests for a given category or how would you approach it?

Seperate stages are not a must thought, just easy to discover but requires seperate agents.

**Comment by stijnmoreels** [comment]
I would have the creation of the projects take on a lower level; in the code itself.
That way, we could run it locally and would the YAML build not be bloated with each time a new testing combination.

**Comment by stijnmoreels** [comment]
I'll to come up with an example in a WIP PR.

**Comment by tomkerkhove** [comment]
Sounds good to me, will be easier to grasp with a sample I think since I'm not sure if fully getting your suggestion - Thanks!

Just keep in mind that we're mainly testing all the options so in theory we need to run a `dotnet new` with the option to make sure that the output is what we are testing.
