### ISSUE TITLE
Provide template for Azure Service Bus worker in Azure Functions

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#244]
**Is your feature request related to a problem? Please describe.**
Provide a template for Azure Service Bus worker in Azure Functions which uses message handler concept with all our best practices baked into it.

**Additional context**
Depends on https://github.com/arcus-azure/arcus.messaging/issues/127

**Comment by stijnmoreels** [comment]
Both for queue and topic? Or is an Azure Function able to switch easily between the two.

**Comment by tomkerkhove** [comment]
It is, ask me again in a week and I'll be able to give you a sample (repo is private for now)

**Comment by stijnmoreels** [comment]
Waiting for https://github.com/arcus-azure/arcus.messaging/issues/127 to be complete.

**Comment by stijnmoreels** [comment]
Waiting for https://github.com/arcus-azure/arcus.templates/pull/265 to be complete since it has some Azure Functions test changes that we can benefit from.
Already have some work done locally, though, with the MyGet package. Looking good!

**Comment by stijnmoreels** [comment]
Waiting for Arcus.Messaging as it's not .NET 6 supported.
