### ISSUE TITLE
Provide template for exposing an HTTP endpoint in Azure Functions

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#245]
**Is your feature request related to a problem? Please describe.**
Provide a template for exposing an HTTP endpoint in Azure Functions with all our best practices baked into it.

**Comment by stijnmoreels** [comment]
Could you give me a rundown of what such an Azure Function project should contain? Correlation? Exception handling configuration? Inputs? content-type restrictionts?

Some more info may be required here.
