### ISSUE TITLE
Provide template for an Azure Function that reports Databrick metrics on a scheduled time

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#246]
**Is your feature request related to a problem? Please describe.**
Provide template for an Azure Function that reports Databrick metrics on a scheduled time

**Comment by stijnmoreels** [comment]
So only a scheduled Azure Function with our background jobs Databricks package?

**Comment by tomkerkhove** [comment]
That's correct, which uses https://background-jobs.arcus-azure.net/preview/features/databricks/gain-insights
