### ISSUE TITLE
Provide logo for our .NET templates

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#297]
**Is your feature request related to a problem? Please describe.**
Provide logo for our .NET templates so that they are shown in the Visual Studio picker.

**Comment by stijnmoreels** [comment]
Should we use the general Arcus logo?

**Comment by tomkerkhove** [comment]
Yes please, but I'm not sure if it's supported at the moment.

if we use it, we should add a white background to it.

**Comment by stijnmoreels** [comment]
Or save as .jpg 😃 .

**Comment by stijnmoreels** [comment]
![image](https://user-images.githubusercontent.com/9039753/108323276-c1928380-71c6-11eb-9258-a51bbf2b32f5.png)

**Comment by tomkerkhove** [comment]
![image](https://user-images.githubusercontent.com/4345663/108490367-fa078f80-72a2-11eb-95e7-6c76b41efb89.png)

This looks odd :D

**Comment by tomkerkhove** [comment]
Light theme looks OK though:

![Uploading image.png…]()

**Comment by tomkerkhove** [comment]
Can we tweak the title so that:
- It no longer has `(Arcus)`
- It no longer has `project template`

**Comment by stijnmoreels** [comment]
> Light theme looks OK though:
> 
> ![image](https://user-images.githubusercontent.com/4345663/108490538-215e5c80-72a3-11eb-8e16-8a3e02d3a44b.png)

Hmm, maybe we should ask marketing to create for us a an icon or so, or well we should use the general Arcus logo without the white background.

**Comment by tomkerkhove** [comment]
I think that's ok actually, will open an issue for VS

**Comment by stijnmoreels** [comment]
> Can we tweak the title so that:
> 
> * It no longer has `(Arcus)`

I think that's the author of the package, so hmm, maybe we should remove the 'Arcus' in the begin of the title.

**Comment by tomkerkhove** [comment]
Fine by me

**Comment by stijnmoreels** [comment]
It's a good thing that the logo works, though 😄 .

**Comment by tomkerkhove** [comment]
Yes, thanks!
