### ISSUE TITLE
Arcus.Templates.AzureFunctions.Http & Health Check

### ISSUE THREAD

**Issue by pim-simons** [arcus-azure/arcus.templates#378]
**Is your feature request related to a problem? Please describe.**
I always include a health check endpoint in my HTTP triggered Azure Functions, that way I can add it to my availability checks in Application Insights and have some pro-active monitoring on my HTTP triggered Functions. Is it possible to add this to the Arcus.Templates.AzureFunctions.Http template? 

**Describe the solution you'd like**
Maybe we can add an opt-in for this in the template. I always use the Azure Function Health Check Library from here: https://github.com/keithsmith21/AzureFunctionHealth, unfortunately there is nu nuget package available for this (https://github.com/keithsmith21/AzureFunctionHealth/issues/1). Maybe we could leverage that or do something similar?

**Describe alternatives you've considered**
Not adding it 😉 

**Additional context**
none

**Comment by tomkerkhove** [comment]
Looks like that project is nice, but no longer maintained.

I would suggest to fork the repo and make it available under `Arcus.WebApi.Health.AzureFunctions` which we can use here. What do you think @stijnmoreels?

**Comment by stijnmoreels** [comment]
Yes, I think that's a good idea. I stared a discussion #320 a while back for this topic.

**Comment by stijnmoreels** [comment]
@pim-simons , is there a reason you choose to use this (https://github.com/keithsmith21/AzureFunctionHealth) library instead of the Microsoft health checks package? The `.AddHealthChecks` is available on the `IServiceCollection` of the `IFunctionsHostBuilder` in your Azure Functions project. As far as we could test is this working for us.

**Comment by pim-simons** [comment]
I never got the Microsoft health check to work, as stated in https://github.com/keithsmith21/AzureFunctionHealth: "The traditional health checks registered in an aspnetcore API included the HealthCheckPublisherHostedService as a HostedService which is not possible or desired to run in an Azure Function.".

But this is from quite some time ago, so maybe things have changed and we can now use the Microsoft package.

**Comment by tomkerkhove** [comment]
Would you mind giving it a go and tell us if it works nowadays? Otherwise it's a bit of a pity to maintain this.

**Comment by pim-simons** [comment]
Will put it on my to-do list 👍

**Comment by pim-simons** [comment]
Just checked, the Microsoft health checks package now work fine as well! So we don't need any extra code for this.
Could be an idea to include something like this in the template:
```
services.AddHealthChecks()
    .AddCheck("Example", () =>
        HealthCheckResult.Healthy("Example is OK!"), tags: new[] { "example" });
```
Just to trigger people to think about health check endpoints as they can be handy in pro-actively monitoring the health of your functions.

**Comment by tomkerkhove** [comment]
Thanks for testing - Let's kill our fork then @stijnmoreels.

Sorry for the trouble.

Let's open an issue for the health check which people can opt-out for then!

**Comment by stijnmoreels** [comment]
Close in favor of #398 . Feel free, @pim-simons , to open another issue when there's still a problem.
