### ISSUE TITLE
 Arcus.Templates.AzureFunctions.Http & OpenAPI

### ISSUE THREAD

**Issue by pim-simons** [arcus-azure/arcus.templates#379]
**Is your feature request related to a problem? Please describe.**
I always include an OpenAPI specification in my HTTP triggered Azure Functions, see: [https://www.codit.eu/blog/adding-swagger-ui-azure-functions/](https://www.codit.eu/blog/adding-swagger-ui-azure-functions/) Is it possible to add this to the Arcus.Templates.AzureFunctions.Http template?

**Describe the solution you'd like**
Maybe we can add an opt-in for this in the template. 
The easiest way to implement is probably to add the Aliencube.AzureFunctions.Extensions.OpenApi nuget package and OpenApi attributes in the template function (also some small additions to the local.settings.json and host.json file), see [https://www.codit.eu/blog/adding-swagger-ui-azure-functions/](https://www.codit.eu/blog/adding-swagger-ui-azure-functions/).

**Describe alternatives you've considered**
Not adding it 😉 

**Additional context**
none

**Comment by tomkerkhove** [comment]
Sounds reasonable to me. Can we fully rely on Aliencube or does it require custom code as well?

**Comment by pim-simons** [comment]
As far as I know it doesn't need any custom code (does ofcourse need OpenApi attributes on your Function method).

**Comment by scleynen** [comment]
In Visual Studio you can choose an Azure Function with OpenAPi specs. It is then using microsoft.azure.webjobs.extensions.openapi nuget package iso AlienCube. Actually it looks quite similar to AlienCube, so I was wondering why not using the microsoft package? 

![image](https://user-images.githubusercontent.com/7026342/121474602-9675af00-c9c4-11eb-998d-1e6afbb0dd28.png)

**Comment by tomkerkhove** [comment]
Preview is the new full release?!
![image](https://user-images.githubusercontent.com/4345663/121475874-47307e00-c9c6-11eb-92f7-7133f740af2f.png)

I don't like the preview aspect but since Microsoft is going this way and Aliencube is archived we should go that route indeed, thanks for raising @scleynen!

https://github.com/aliencube/AzureFunctions.Extensions

**Comment by pim-simons** [comment]
Using the Microsoft package seems like a good solution!

**Comment by stijnmoreels** [comment]
So, we wait until it's out of preview?

**Comment by tomkerkhove** [comment]
It's ok to go ahead with it

**Comment by stijnmoreels** [comment]
Ok, should we opt-in for this or like the web API template opt-out?

**Comment by tomkerkhove** [comment]
Let's use opt-out to align

**Comment by stijnmoreels** [comment]
I've got something ready locally, preparing a draft PR till it's out of preview.

**Comment by pim-simons** [comment]
> 
> 
> I've got something ready locally, preparing a draft PR till it's out of preview.

It recently went out of preview: https://github.com/Azure/azure-functions-openapi-extension/releases/tag/v1.0.0 🥳

**Comment by stijnmoreels** [comment]
> > I've got something ready locally, preparing a draft PR till it's out of preview.
> 
> It recently went out of preview: https://github.com/Azure/azure-functions-openapi-extension/releases/tag/v1.0.0 🥳

Aha aha! Great! 🎉 We'll take a look at it in #415 . Thx for mentioning it!
