### ISSUE TITLE
Support .NET 6

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#464]
Since .NET 6 has been released, and .NET 6 is the latest LTS version, we should start supporting templates that are based on .NET 6.

I don't know if we should still support .NET Core 3.1 as well ? Maybe default to .NET 6 and provide a parameter to generate a project for .NET Core 3.1 ?   Although this will be something that we'll only support for a short term as .NET Core 3.1 support ends in december 2022.

**Comment by stijnmoreels** [comment]
Let's close this in favor of https://github.com/arcus-azure/arcus/issues/106 as we should do this for all repo's.
