### ISSUE TITLE
HealthReport types cause that additional (unwanted) types end up in the OpenApi definition

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#491]
When we create an API project using the Arcus template, we get a Health endpoint for free, which is a good thing.

However, the models that are used by this endpoint to create the response have a nasty side-effect:  The Open API specification for our API suddenly includes schema-information for types that consumers of the API are actually not interested in.  In other words, our OpenAPI documentation gets polluted.
It looks like types from System.Reflection are included:

![image](https://user-images.githubusercontent.com/3605786/145550182-48e68444-c55a-4806-95ef-1e5e0c5a3d93.png)

It's easy to work around this, by removing the `ProducedResponseType` attributes from the health-endpoint, however, then the OpenAPI documentation is not complete.

I wonder if we should use a custom type for the response-model of the health-endpoint, as it is clear the the `HealthReport` types cause this pollution.

**Comment by stijnmoreels** [comment]
Hmm, I'm even wondering if we use the `HealthReport` type 🤔. I think we even use `string` as general response type.

**Comment by stijnmoreels** [comment]
I think we even use `string` in Azure Functions bc `HealthReport` gave errors 🤔.

**Comment by fgheysels** [comment]
This is what the health endpoint returns
```json
{
  "entries": {},
  "status": "Healthy",
  "totalDuration": "00:00:00.0000078"
}
```

**Comment by stijnmoreels** [comment]
Maybe schema filters is an option here too?

**Comment by stijnmoreels** [comment]
The `HealthReport` has an `Exception` has `HealthReportEntry` property; I think this leads to this unwanted tree of related types.
A dedicated JSON data transfer object is maybe a good idea. This is something we could consider for the other project templates too.

**Comment by fgheysels** [comment]
Could indeed be that the Exception property causes this, but should we even include exception information in the response of that health-endpoint request ?
I'd say we create our own HealthReport API model for this, which does not include exception info.

**Comment by stijnmoreels** [comment]
Yes, that would be better, indeed. We may even opt to expose this separately in `Arcus.WebApi` so we can both use it in our templates as well as in the TCP probe in Messaging.
