### ISSUE TITLE
406 is returned when Accept header is text/plain

### ISSUE THREAD

**Issue by MassimoC** [arcus-azure/arcus.templates#50]
406 is returned when the client send the Accept: text/plain

How to fix this?
* remove the text plain as supported media type for JsonOutputFormatter?
```csharp
            var jsonOutputFormatter = options.OutputFormatters.OfType<JsonOutputFormatter>().FirstOrDefault();
            if (jsonOutputFormatter != null)
            {
                if (!jsonOutputFormatter.SupportedMediaTypes.Contains(Text.Plain))
                {
                    jsonOutputFormatter.SupportedMediaTypes.Add(Text.Plain);
                }
            }
```
* remove the text plain as supported media type for JsonInputFormatter? 
```csharp
            var jsonInputFormatter = options.InputFormatters.OfType<JsonInputFormatter>().FirstOrDefault();
            if (jsonInputFormatter != null)
            {
                if (jsonInputFormatter.SupportedMediaTypes.Contains(Text.Plain))
                {
                    jsonInputFormatter.SupportedMediaTypes.Remove(Text.Plain);
                }
            }
```
*  understand why the StringOutputFormatter doesn't kick in.
StringOutputFormatter is added by default and according to the [docs](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md) it should take care of text/plain
If not used / if doesn't kick in, better to remove
```csharp
            var stringFormatter = options.OutputFormatters.OfType<StringOutputFormatter>().FirstOrDefault();
            if (stringFormatter != null) options.OutputFormatters.RemoveType<StringOutputFormatter>();
```

**Comment by stijnmoreels** [comment]
Not sure if I understand correctly; why should we fix this? Should we allow text/plain responses?

**Comment by tomkerkhove** [comment]
We should fix it because if you now create a new API off of the template it doesn't work in Swagger UI because it uses `text/plain`.

Since we restrict it to support `application/json` by default, as per @MassimoC's request, it is not able to handle this so it returns a 406.

Personally I think we should check why Swagger UI is trying to use `text/plain` and change that.

**Comment by fgheysels** [comment]
On a related note:  If you run the unittests in the arcus web.api package, you'll also see that the statuscode 'unsupported mediatype' is being returned.

**Comment by fgheysels** [comment]
When your client sends text/plain, it means that you are going to support it in your api imho.
Anyway, I have created an api using the template but I haven't succeeded in reproducing this until now

**Comment by MassimoC** [comment]
Guys, there is nothing wrong with the swagger ui!
* the OpenAPI file clearly states the API is supporting text/plain
![image](https://user-images.githubusercontent.com/8393694/67519916-24920a00-f6a8-11e9-8bca-fe0de0139a44.png)

* so, as consumer, I am feel free to ask for a response formatted in text/plain (content negotiation). If everything works as it should a 200 is returned. In this case I got 406 and this is **NOT OK**.
![image](https://user-images.githubusercontent.com/8393694/67519994-4b504080-f6a8-11e9-88df-d67ed07221e7.png)
The following make sense, when I ask for something that is not supported, i got a 406
![image](https://user-images.githubusercontent.com/8393694/67520243-bac63000-f6a8-11e9-8515-1ff1f6969d5e.png)


So a decision should be taken, either
* fix the API to make sure it supports all the media types have been declared in the "produces" field. For example, the output formatter is there, why doesn't kick in?
![image](https://user-images.githubusercontent.com/8393694/67520431-1abcd680-f6a9-11e9-982c-a5f29a468edd.png)

* remove the mediatypes that you do not support from the "produces"
![image](https://user-images.githubusercontent.com/8393694/67520690-9a4aa580-f6a9-11e9-9bb9-874e670b2e7e.png)

**Comment by tomkerkhove** [comment]
Let's just update the OpenAPI spec to only list application/json

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

Tom Kerkhove
Architect - Microsoft Azure Advisor & MVP
m: +32 473 70 10 74
tom.kerkhove@codit.eu | www.codit.eu

**Comment by tomkerkhove** [comment]
@MassimoC Feel free to have a look at #60 which provides OpenAPI docs that are in line with the actual API which only supports `application/json` since we restrict it to only JSON (see `RestrictToJsonContentType`)

However, it's only restricting the input and is expected use-case according to https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/web-api/advanced/formatting.md#the-accept-header

**Comment by tomkerkhove** [comment]
Took this offline with @MassimoC and found out that removing `StringOutputFormatter` is best approach like he suggested.

Result:
![image](https://user-images.githubusercontent.com/4345663/67950746-868fc980-fbea-11e9-9bc4-b3236e429a1a.png)

![image](https://user-images.githubusercontent.com/4345663/67950767-90b1c800-fbea-11e9-947d-71064cf7157d.png)
