### ISSUE TITLE
Better error message when the Azure Functions Core Tools are not installed

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.templates#503]
**Is your feature request related to a problem? Please describe.**
Currently, when the self-contained integration tests run we use the installed Azure Functions Core Tools. But when this is not installed, we get a general 'File not found' exception.

**Describe the solution you'd like**
Add an extra control to verify if the tools are installed and provide the developer with a better error message.

**Comment by fgheysels** [comment]
I think it is a great thing if we can improve developer experience;, so this is definitely something we must do.
