### ISSUE TITLE
Remove 'Server' header from web API template

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.templates#51]
## Problem
No need to leak information about the web API in the `Server:` HTTP header, so we need to hide this header from every response.

## Proposal
The kestrel options as a `boolean` called `AddServerHeader` to configure this.

## Resources
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserveroptions.addserverheader?view=aspnetcore-3.0

**Comment by tomkerkhove** [comment]
Happy to pick this up!
