### ISSUE TITLE
Replace Microsoft.Azure.ApplicationInsights.Query dependency

### ISSUE THREAD

**Issue by scottaddie** [arcus-azure/arcus.templates#539]
Last week, the Azure SDK team deprecated Microsoft.Azure.ApplicationInsights.Query in favor of [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query). Please make plans to migrate. Migration guidance has been provided at https://aka.ms/azsdk/net/migrate/ai-monitor-query.

Per [this announcement](https://azure.microsoft.com/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/), support for this deprecated package ends on March 31, 2023.

**Comment by fgheysels** [comment]
We're using this package in our Integration Tests project for Arcus.Templates.

**Comment by stijnmoreels** [comment]
The Azure Monitory Query update is not yet dev-friendly enough for it to be used here. Closing for now.
