### ISSUE TITLE
Provide template for Azure Service Bus worker consuming a Topic in Azure Functions

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#562]
It is very similar to [this](https://github.com/arcus-azure/arcus.templates/issues/244) request.
I think we should also provide a project template for a Function that consumes messages that are published to a topic, using a given subscriber.

**Comment by stijnmoreels** [comment]
Yes, of course, I thought #244 was clear on that that we need both, but we can create a dedicated issue for that here, sure!
