### ISSUE TITLE
[Arcus template for HTTP-Triggered Function App]: Warning deprecated & Error when upgraded to Arcus version 2.4

### ISSUE THREAD

**Issue by ACA-CDT** [arcus-azure/arcus.templates#575]
**Describe the bug**
For the new Monitoring I use an Arcus template for a HTTP-triggered Azure Function. Arcus version 2.2.2 works well in .Net Core 3.1 and .Net 6.0, but there's a deprecated warning in one of the NuGet packages of Arcus:
![image](https://user-images.githubusercontent.com/86767115/165913766-1d45942d-0fbd-43af-9b31-94206a4e2358.png)

- when I upgrade the Arcus NuGet Packages to Arcus version 2.4, an error and warning is shown on these lines:
![image](https://user-images.githubusercontent.com/86767115/165914821-2627cb4b-c51b-4879-95bb-1428e6228315.png)

![image](https://user-images.githubusercontent.com/86767115/165915460-853c92fa-18b2-4d14-90e5-6d548fb97425.png)

**To Reproduce**
- Follow the instructions in the Arcus documentation to create a new Function App project using the Arcus Template: https://templates.arcus-azure.net/features/azurefunctions-http-template
- Upgrade the NuGet Packages to their last version
- Upgrade the project to .NET 6.0

**Expected behavior**
If possible, a plug-and-play Function App Arcus project template for .Net Core 3.1 & .NET 6.0 with the last versions of Arcus without deprecated packages or code marked as obsolete

**Comment by pim-simons** [comment]
Don't replace the `Arcus.Observability.Telemetry.AzureFunctions` package just yet, see also https://github.com/arcus-azure/arcus.observability/issues/364

**Comment by stijnmoreels** [comment]
Thx for mentioning. The two packages mentioned are already under consideration. At the moment, we can't update the HTTP correlation extension because we are migrating towards another one and will only be available in v2.0 of Arcus WebAPI. The other extension is also under consideration is will possibly be made 'undeprecated' like Pim said.

**Comment by HelenaCoppieters** [comment]
Ok, Thx, I'll keep it in mind.

**Comment by stijnmoreels** [comment]
@fgheysels , will we provide default-provided options so to guide consumers to the non-deprecated variant?

**Comment by stijnmoreels** [comment]
We could actually also move the currently located `HttpCorrelationInfoOptions.Upstream` property in Web API to the `CorrelationInfoOptions` in Observability library, as upstream services can be used outside Web API applications, that way we could actually remove back the `HttpCorrelationInfoOptions`, and refactor the optional argument extension to method overloading without waiting for the next major.

**Comment by stijnmoreels** [comment]
@ACA-CDT , we updated the project templates to .NET 6 and the next version v1.1 will also include the new W3C correlation. Normally, any package deprecation issues should be fixed now. Can we close this?
