### ISSUE TITLE
Remove unnecessary middleware method to load client certificate from request header

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.templates#58]
## Problem
The `Startup` class still has a middleware method to load the client certificate from the `X-ARR-ClientCert` header. This will become unnecessary since the `CertificateAuthenticationFilter` will automatically load this in the future.

## Solution
This filter is part of the [arcus.webapi](https://github.com/arcus-azure/arcus.webapi) repo and will become available for all versions above **v.0.2.0**.

**Comment by tomkerkhove** [comment]
In what issue in arcus.webapi are we tracking the initial fix @stijnmoreels ?

**Comment by stijnmoreels** [comment]
> In what issue in arcus.webapi are we tracking the initial fix @stijnmoreels ?

The fix for this problem exists here, we have to remove some code because it's already included in the upcoming NuGet of the Arcus.WebApi. So no issue in Arcus.WebApi repo, right?

**Comment by tomkerkhove** [comment]
I was indeed referring to the change in WebAPI to know what the status is of that given no issue was mentioned.

Was it https://github.com/arcus-azure/arcus.webapi/issues/31 which is part of 0.2.0?

**Comment by stijnmoreels** [comment]
> I was indeed referring to the change in WebAPI to know what the status is of that given no issue was mentioned.
> 
> Was it [arcus-azure/arcus.webapi#31](https://github.com/arcus-azure/arcus.webapi/issues/31) which is part of 0.2.0?

It was this one: https://github.com/arcus-azure/arcus.webapi/issues/72

**Comment by tomkerkhove** [comment]
Feel free to trigger a release so you can use it here

**Comment by stijnmoreels** [comment]
What would the next version be? v0.3.0?

**Comment by tomkerkhove** [comment]
Yes, similar to the milestone - https://github.com/arcus-azure/arcus.webapi/milestone/4 (although we don't assign patch versions for those, but `0.3.0` should be new NuGet version)

**Comment by stijnmoreels** [comment]
Hmm, 'invalid assembly version format' ? Locally, this is set to 1.0.0.0; but I guess we don't use this and use directly the NuGet version in the YAML builds?
https://dev.azure.com/codit/Arcus/_build/results?buildId=39382&view=logs&j=143eea66-4597-539b-c2e7-6e457837a569&t=9f621ec8-3fd0-5ad3-fb9c-a4413470200a

**Comment by tomkerkhove** [comment]
Let's open an issue on https://github.com/arcus-azure/arcus.webapi and discuss there ;)
