### ISSUE TITLE
Use direct references for Observability packages instead of transient via WebAPI/Messaging

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.templates#596]
**Is your feature request related to a problem? Please describe.**
Currently, we don't use every Observability package directly in the project templates. Some packages are only transient there via WebAPI or Messaging packages. This leads to long updates as we first have to wait for those libraries to update before that the templates can benefit from the new observability functionality.

**Describe the solution you'd like**
Make sure that every project template uses directly the Observability package instead of relying on the transient references via WebAPI/Messaging.

**Comment by fgheysels** [comment]
I think this might be a good idea. :)
