### ISSUE TITLE
Use custom `ApiHealthReport` in Azure Functions HTTP trigger project template

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.templates#600]
**Is your feature request related to a problem? Please describe.**
We added a custom `ApiHealthReport` model to the Web API project template so internal assembly information doesn't get exposed via exception details. The Azure Functions HTTP trigger template also has a function that exposes the health of the application but is still using directly Microsoft's `HealthReport`.

**Describe the solution you'd like**
Add the `ApiHealthReport` API model to the Azure Functions HTTP trigger project template so that we don't expose internal assembly information via exception details when the health report is unhealthy.

**Additional context**
Follow-up of #589 
Relates to #491

**Comment by vtermaat** [comment]
@stijnmoreels starting on this
