### ISSUE TITLE
HTTP triggered Function template is still using the obsolete AddHttpCorrelation extension method 

### ISSUE THREAD

**Issue by pim-simons** [arcus-azure/arcus.templates#601]
When creating a new HTTP triggered Function project (https://templates.arcus-azure.net/features/azurefunctions-http-template/) , the project is still using the now obsolete AddHttpCorrelation() extension method: `builder.AddHttpCorrelation();`.

This should be changed to the non-obsolete version.
Related to https://github.com/arcus-azure/arcus.templates/issues/538 but now applied to the HTTP triggered Function project.

**Comment by stijnmoreels** [comment]
Yeah, that's a pickle.
<img src="https://media1.giphy.com/media/JmPenP1svctdfDCEHi/giphy.gif"/>

Also related to #575

**Comment by stijnmoreels** [comment]
Updated to Arcus.WebApi v1.6 which fixes this.
