### ISSUE TITLE
WebApi template improvement: add APPINSIGHTS_INSTRUMENTATIONKEY to appsettings.json

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#602]
When you create a new WebApi using the Arcus template, code is generated to enable application insights logging.
In the code, you can find this:
![image](https://user-images.githubusercontent.com/3605786/172610706-6b7df731-a66c-4ff6-9317-626cd091c4b6.png)

But the appsettings.json file that is included in the project, doesn't include a property for `APPINSIGHTS_INSTRUMENTATIONKEY`.  I think it would be good if we would add an empty property to the appsettings.json file.

**Comment by stijnmoreels** [comment]
Then, we have to make sure that the property value is indeed empty, and we don't have an argument exception because that would only make it less user-friendly.

**Comment by fgheysels** [comment]
> Then, we have to make sure that the property value is indeed empty, and we don't have an argument exception because that would only make it less user-friendly.

As I remember, we've changed this so that no exception is thrown when the instrumentation-key is empty.

**Comment by stijnmoreels** [comment]
> > Then, we have to make sure that the property value is indeed empty, and we don't have an argument exception because that would only make it less user-friendly.
> 
> As I remember, we've changed this so that no exception is thrown when the instrumentation-key is empty.

Yes, exactly, so we can only provide an blank value to the application property, and can't for example use a format like `<instrumentation-key>` as we did with other settings.
