### ISSUE TITLE
Rename the 'Serilog' compiler directive

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#625]
In the WebApi template, we have a conditional directive which is called `Serilog`.
I think we can improve this by giving it a better name, as this conditional actually means:  do you want to use Arcus logging via Serilog (and it then also includes the sink to App Insights).

Proposals for a new name:
- Arcus_AppInsights
- Serilog_AppInsights
- Arcus_Logging
- ...

or any other variant :)

**Comment by stijnmoreels** [comment]
Definitely include the `Serilog`-part, as the project option is called `Serilog`, and otherwise it would be misleading, as we try to make sure that the directs match with the available project options to quickly see what gets activated in the code.

**Comment by stijnmoreels** [comment]
Also, question: we have explicitly added an `if` statement to make sure that blank Application Insights instrumentationkey/connectionstring doesn't stop the logging. So, it is also perfectly safe to start a project without that sink.
But then the directive would be misleading, no?
