### ISSUE TITLE
Discussion - Include Marvin.StreamExtensions in template

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.templates#66]
[Marvin.StreamExtensions](https://github.com/KevinDockx/StreamExtensions) includes basic functionality to interact with streams which I've found myself implementing myself as well.

Might be interesting to include it rather than building our own.

```csharp
using (var response = await httpClient.SendAsync(request))
{
    using (var stream = await response.Content.ReadAsStreamAsync())
    {
        var person = stream.ReadAndDeserializeFromJson<Person>();
    }
}
```

**Comment by stijnmoreels** [comment]
Newtownsoft also has read from stream I think.

With `StreamReader`.

**Comment by tomkerkhove** [comment]
Are you referring to this?

**Comment by MassimoC** [comment]
Where do we draw the line on what should be added in the default template and what not? I mean, there are tons of very good extensions / middlewares out there ... Should we add them all, only few, none?

**Comment by tomkerkhove** [comment]
It's a balance that we have to find but if it's something that we use a lot & has been proven then we should add it.

But to your point, since we haven't used this one before I'll close this one for now.

**Comment by stijnmoreels** [comment]
> Are you referring to [this](https://www.newtonsoft.com/json/help/html/DeserializeWithJsonSerializerFromFile.htm)?

No, you can use `JsonTextReader`.

```csharp
var loadSettings = new JsonLoadSettings
{
    DuplicatePropertyNameHandling = DuplicatePropertyNameHandling.Error
};

using var strReader = new StreamReader(content);
using var txtReader = new JsonTextReader(strReader);
JObject.Load(txtReader, loadSettings);
```
