### ISSUE TITLE
Streamline `launchSettings.json` in project templates

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.templates#764]
**Is your feature request related to a problem? Please describe.**
Currently, we have some project templates that have a `/Properties/launchSettings.json` file and others don't. This is not consistent.

**Describe the solution you'd like**
Make sure that every project template has a `/Properties/launchSettings.json` file that both works with Docker and the project itself, so developers can both easily start the project via Docker or by itself.

**Comment by fgheysels** [comment]
This is only relevant for Web API project templates, isn't it ?

**Comment by stijnmoreels** [comment]
> This is only relevant for Web API project templates, isn't it ?

No, there are project templates (like the Service Bus topic worker) that do not have such settings file, while others (like the Service Bus queue worker) has.
