### ISSUE TITLE
Function template: --functions-worker option does not seem to work

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#779]
I might be wrong here

**Comment by stijnmoreels** [comment]
Can we remove this, then? 😉

**Comment by fgheysels** [comment]
I don't seem to have the rights to do that.

**Comment by stijnmoreels** [comment]
Closing the issue, with 'not planned' will it be.

![image](https://user-images.githubusercontent.com/9039753/218453564-56cd5650-b62d-42cc-98ed-24b8b4a83e61.png)
