### ISSUE TITLE
Documentation in Arcus Templates 

### ISSUE THREAD

**Issue by gverstraete** [arcus-azure/arcus.templates#841]
When I install the Arcus Templates via:
`dotnet new --install Arcus.Templates.WebApi`

I get this: 
![image](https://github.com/arcus-azure/arcus.templates/assets/31242865/4efaeb58-db6d-46b0-aec5-7fbe1f5df577)

So I think the docs should be updated.

**Comment by stijnmoreels** [comment]
Thx! Updated in #874
