### ISSUE TITLE
Suggested Secret Key Name is incompatible with Azure KeyVault

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.templates#858]
When creating a new project based on the Arcus Messaging template, some code is generated for you for retrieving the Application Insights connectionstring from a secret-store.

One of the generated parts, is the name of the configuration or secret key that contains the app insights connectionstring:

```
 #warning Make sure that the Azure Application Insights connection string key is available as a secret.
 private const string ApplicationInsightsConnectionStringKeyName = "APPLICATIONINSIGHTS_CONNECTION_STRING";
```

However, when using Azure KeyVault as a secret-provider, you cannot use the suggested name, as KeyVault doesn't allow to have underscores in it's secret name.

So, what shall we do ?
- leave as it is, and cause a little bit of annoyance 
- use another name that doesn't contain underscores ?  (hyphens are allowed)

**Comment by fgheysels** [comment]
The same is actually true for the servicebus connectionstring:

![image](https://github.com/arcus-azure/arcus.templates/assets/3605786/32a2062e-91ba-408e-b8b7-323688b7739c)

**Comment by Lilneo786** [comment]
private const string ApplicationInsightsConnectionStringKeyName = "application-insights-connection-string";

**Comment by stijnmoreels** [comment]
* Or use the mutated secret name functionality and have best of both worlds?

**Comment by fgheysels** [comment]
Good point, forgot about that one. :D
