### ISSUE TITLE
Feature - add web API project option for JWT role-based authentication

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.templates#89]
**What feature would you like to have?**
In any app, there may come a time where you want to limit access for diff authenticated users.. Right now, we allow _all_ features of any API by a single shared access key or configured certificate.
I think it would be useful to add also a JWT authentication system with roles for authorization for a more fine-grained control?

**Alternatives you may have considered?**
We could also add the possibility to use different kinds of shared access keys/certificates for different levels of access in the API. Maybe also with roles.

**Comment by tomkerkhove** [comment]
That's certainly interesting but I'm not sure if it should be part of the template, but if it's small effort - Why not.

**Comment by stijnmoreels** [comment]
> That's certainly interesting but I'm not sure if it should be part of the template, but if it's small effort - Why not.

Which one do you mean? The JWT approach or the access level approach on shared access key/certificate?

**Comment by tomkerkhove** [comment]
The JWT approach and what it would look like (no experience on that front)
